LANGUAGES = {
    "tr": {
        "add_part": "Parça Ekle",
        "edit_part": "Parça Düzenle",
        "delete_part": "Seçiliyi Sil",
        "delete_all_parts": "Tümünü Sil",
        "optimize": "Optimize Et",
        "error_invalid_input": "Geçersiz giriş! Lütfen pozitif sayılar girin.",
        "warning_select_part": "Lütfen önce bir parça seçin.",
        "confirm_delete_all": "Tüm parçalar silinecek. Emin misiniz?",
        "ready": "Hazır",
        "optimization_complete": "Optimizasyon tamamlandı.",
        "optimization_error": "Optimizasyon sırasında hata oluştu.",
        "settings": "Ayarlar",
        "file": "Dosya",
        "theme": "Tema",
        "settings_menu": "Ayarlar",
        "help": "Yardım",
        "about": "Hakkında",
        "exit": "Çıkış",
        "project_save": "Projeyi Kaydet",
        "project_load": "Projeyi Yükle",
        "import_csv": "CSV'den İçe Aktar",
        "export_csv": "CSV'ye Dışa Aktar",
        "export_pdf": "PDF'e Dışa Aktar",
        "export_excel": "Excel'e Dışa Aktar",
        "theme_select": "Tema Seç",
        "language_select": "Dil Seçimi",
        "english": "İngilizce",
        "german": "Almanca",
        "french": "Fransızca",
        "spanish": "İspanyolca",
        "turkish": "Türkçe",
        "italian": "İtalyanca"
    },
    "en": {
        "add_part": "Add Part",
        "edit_part": "Edit Part",
        "delete_part": "Delete Selected",
        "delete_all_parts": "Delete All",
        "optimize": "Optimize",
        "error_invalid_input": "Invalid input! Please enter positive numbers.",
        "warning_select_part": "Please select a part first.",
        "confirm_delete_all": "All parts will be deleted. Are you sure?",
        "ready": "Ready",
        "optimization_complete": "Optimization completed.",
        "optimization_error": "Error occurred during optimization.",
        "settings": "Settings",
        "file": "File",
        "theme": "Theme",
        "settings_menu": "Settings",
        "help": "Help",
        "about": "About",
        "exit": "Exit",
        "project_save": "Save Project",
        "project_load": "Load Project",
        "import_csv": "Import CSV",
        "export_csv": "Export CSV",
        "export_pdf": "Export PDF",
        "export_excel": "Export Excel",
        "theme_select": "Select Theme",
        "language_select": "Select Language",
        "english": "English",
        "german": "German",
        "french": "French",
        "spanish": "Spanish",
        "turkish": "Turkish",
        "italian": "Italian"
    },
    "de": {
        "add_part": "Teil hinzufügen",
        "edit_part": "Teil bearbeiten",
        "delete_part": "Auswahl löschen",
        "delete_all_parts": "Alle löschen",
        "optimize": "Optimieren",
        "error_invalid_input": "Ungültige Eingabe! Bitte positive Zahlen eingeben.",
        "warning_select_part": "Bitte zuerst ein Teil auswählen.",
        "confirm_delete_all": "Alle Teile werden gelöscht. Sind Sie sicher?",
        "ready": "Bereit",
        "optimization_complete": "Optimierung abgeschlossen.",
        "optimization_error": "Fehler bei der Optimierung aufgetreten.",
        "settings": "Einstellungen",
        "file": "Datei",
        "theme": "Thema",
        "settings_menu": "Einstellungen",
        "help": "Hilfe",
        "about": "Info",
        "exit": "Beenden",
        "project_save": "Projekt speichern",
        "project_load": "Projekt laden",
        "import_csv": "CSV importieren",
        "export_csv": "CSV exportieren",
        "export_pdf": "PDF exportieren",
        "export_excel": "Excel exportieren",
        "theme_select": "Thema wählen",
        "language_select": "Sprache wählen",
        "english": "Englisch",
        "german": "Deutsch",
        "french": "Französisch",
        "spanish": "Spanisch",
        "turkish": "Türkisch",
        "italian": "Italienisch"
    },
    "fr": {
        "add_part": "Ajouter une pièce",
        "edit_part": "Modifier la pièce",
        "delete_part": "Supprimer la sélection",
        "delete_all_parts": "Tout supprimer",
        "optimize": "Optimiser",
        "error_invalid_input": "Entrée invalide ! Veuillez saisir des nombres positifs.",
        "warning_select_part": "Veuillez d'abord sélectionner une pièce.",
        "confirm_delete_all": "Toutes les pièces seront supprimées. Êtes-vous sûr ?",
        "ready": "Prêt",
        "optimization_complete": "Optimisation terminée.",
        "optimization_error": "Erreur survenue lors de l'optimisation.",
        "settings": "Paramètres",
        "file": "Fichier",
        "theme": "Thème",
        "settings_menu": "Paramètres",
        "help": "Aide",
        "about": "À propos",
        "exit": "Quitter",
        "project_save": "Sauvegarder le projet",
        "project_load": "Charger le projet",
        "import_csv": "Importer CSV",
        "export_csv": "Exporter CSV",
        "export_pdf": "Exporter PDF",
        "export_excel": "Exporter Excel",
        "theme_select": "Choisir le thème",
        "language_select": "Choisir la langue",
        "english": "Anglais",
        "german": "Allemand",
        "french": "Français",
        "spanish": "Espagnol",
        "turkish": "Turc",
        "italian": "Italien"
    },
    "es": {
        "add_part": "Agregar pieza",
        "edit_part": "Editar pieza",
        "delete_part": "Eliminar selección",
        "delete_all_parts": "Eliminar todo",
        "optimize": "Optimizar",
        "error_invalid_input": "Entrada inválida! Por favor ingrese números positivos.",
        "warning_select_part": "Por favor seleccione una pieza primero.",
        "confirm_delete_all": "Se eliminarán todas las piezas. ¿Está seguro?",
        "ready": "Listo",
        "optimization_complete": "Optimización completada.",
        "optimization_error": "Error ocurrido durante la optimización.",
        "settings": "Configuración",
        "file": "Archivo",
        "theme": "Tema",
        "settings_menu": "Configuraciones",
        "help": "Ayuda",
        "about": "Acerca de",
        "exit": "Salir",
        "project_save": "Guardar proyecto",
        "project_load": "Cargar proyecto",
        "import_csv": "Importar CSV",
        "export_csv": "Exportar CSV",
        "export_pdf": "Exportar PDF",
        "export_excel": "Exportar Excel",
        "theme_select": "Seleccionar tema",
        "language_select": "Seleccionar idioma",
        "english": "Inglés",
        "german": "Alemán",
        "french": "Francés",
        "spanish": "Español",
        "turkish": "Turco",
        "italian": "Italiano"
    },
    "it": {
        "add_part": "Aggiungi pezzo",
        "edit_part": "Modifica pezzo",
        "delete_part": "Elimina selezionato",
        "delete_all_parts": "Elimina tutto",
        "optimize": "Ottimizza",
        "error_invalid_input": "Input non valido! Inserisci numeri positivi.",
        "warning_select_part": "Seleziona prima un pezzo.",
        "confirm_delete_all": "Tutti i pezzi saranno eliminati. Sei sicuro?",
        "ready": "Pronto",
        "optimization_complete": "Ottimizzazione completata.",
        "optimization_error": "Errore durante l'ottimizzazione.",
        "settings": "Impostazioni",
        "file": "File",
        "theme": "Tema",
        "settings_menu": "Impostazioni",
        "help": "Aiuto",
        "about": "Informazioni",
        "exit": "Esci",
        "project_save": "Salva progetto",
        "project_load": "Carica progetto",
        "import_csv": "Importa CSV",
        "export_csv": "Esporta CSV",
        "export_pdf": "Esporta PDF",
        "export_excel": "Esporta Excel",
        "theme_select": "Seleziona tema",
        "language_select": "Seleziona lingua",
        "english": "Inglese",
        "german": "Tedesco",
        "french": "Francese",
        "spanish": "Spagnolo",
        "turkish": "Turco",
        "italian": "Italiano"
    }
}

DEFAULT_LANGUAGE = "tr"
DEFAULT_THEME = "clam"
DEFAULT_STOCK_LENGTH = 6000  # mm
DEFAULT_KERF = 3  # mm
